server:
  port: 9090
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: address-migrator
  cloud:
    consul:
      discovery:
        hostname: 'localhost'
        port: ${server.port}
        include-hostname-in-instance-id: true
  batch:
    lightmin:
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
        discovery:
          server-discovery-name: spring-batch-lightmin-server
      batch:
        #default jdbc
        repository-type: jdbc
        #default dataSource
        data-source-name: dataSource
        #default BATCH_
        table-prefix: BATCH_
      repository:
        remote:
          discover-remote-repository: true
          server-discovery-name: spring-batch-lightmin-server